const languages = [
  { label: "Ada", value: "ada" },
  { label: "Assembly", value: "asm" },
  { label: "Bash", value: "shell" },
  { label: "C", value: "c" },
  { label: "C#", value: "csharp" },
  { label: "C++", value: "cpp" },
  { label: "Clojure", value: "clojure" },
  { label: "COBOL", value: "cobol" },
  { label: "CSS", value: "css" },
  { label: "Dart", value: "dart" },
  { label: "Dockerfile", value: "dockerfile" },
  { label: "Elixir", value: "elixir" },
  { label: "Erlang", value: "erlang" },
  { label: "Fortran", value: "fortran" },
  { label: "F#", value: "fsharp" },
  { label: "Go", value: "go" },
  { label: "GraphQL", value: "graphql" },
  { label: "Groovy", value: "groovy" },
  { label: "Haskell", value: "haskell" },
  { label: "HTML", value: "html" },
  { label: "INI", value: "ini" },
  { label: "Java", value: "java" },
  { label: "JavaScript", value: "javascript" },
  { label: "JSON", value: "json" },
  { label: "Julia", value: "julia" },
  { label: "Kotlin", value: "kotlin" },
  { label: "Less", value: "less" },
  { label: "Lua", value: "lua" },
  { label: "Markdown", value: "markdown" },
  { label: "MATLAB", value: "matlab" },
  { label: "Nginx", value: "nginx" },
  { label: "Objective-C", value: "objective-c" },
  { label: "Perl", value: "perl" },
  { label: "PHP", value: "php" },
  { label: "Plain Text", value: "plaintext" },
  { label: "PowerShell", value: "powershell" },
  { label: "Prolog", value: "prolog" },
  { label: "Python", value: "python" },
  { label: "R", value: "r" },
  { label: "Ruby", value: "ruby" },
  { label: "Rust", value: "rust" },
  { label: "Sass", value: "sass" },
  { label: "Scala", value: "scala" },
  { label: "SCSS", value: "scss" },
  { label: "Solidity", value: "sol" },
  { label: "SQL", value: "sql" },
  { label: "Swift", value: "swift" },
  { label: "TOML", value: "toml" },
  { label: "TypeScript", value: "typescript" },
  { label: "Verilog", value: "verilog" },
  { label: "VHDL", value: "vhdl" },
  { label: "Visual Basic", value: "vb" },
  { label: "XML", value: "xml" },
  { label: "YAML", value: "yaml" },
];

languages.sort((a, b) => a.label.localeCompare(b.label));

export default languages;
